/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package contadorprioridad;

import java.awt.Graphics;

/**
 *
 * @author jose
 */
public class PanelContadores extends javax.swing.JPanel {

    /**
     * Creates new form PanelContadores
     */
    HiloContador hc1, hc2, hc3;
    public PanelContadores() {
        initComponents();
        hc1=new HiloContador(this);
        hc2=new HiloContador(this);
        hc3=new HiloContador(this);
        
        hc1.setPriority(Thread.NORM_PRIORITY);
        hc2.setPriority(Thread.NORM_PRIORITY);
        hc3.setPriority(Thread.NORM_PRIORITY);
                
        hc1.start();
        hc2.start();
        hc3.start();

    }

    public void paint(Graphics g){
        super.paint(g);
        this.lblContHilo1.setText(hc1.getCont()+"");
        this.lblContHilo2.setText(hc2.getCont()+"");
        this.lblContHilo3.setText(hc3.getCont()+"");
        
        this.lblPrioridadHilo1.setText(hc1.getPriority()+"");
        this.lblPrioridadHilo2.setText(hc2.getPriority()+"");
        this.lblPrioridadHilo3.setText(hc3.getPriority()+"");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMasPrioridad1 = new javax.swing.JButton();
        btnMasPrioridad2 = new javax.swing.JButton();
        btnMasPrioridad3 = new javax.swing.JButton();
        btnFinalizar1 = new javax.swing.JButton();
        btnFinalizar2 = new javax.swing.JButton();
        btnFinalizar3 = new javax.swing.JButton();
        btnMenosPrioridad1 = new javax.swing.JButton();
        btnMenosPrioridad2 = new javax.swing.JButton();
        btnMenosPrioridad3 = new javax.swing.JButton();
        btnFinalizarTodos = new javax.swing.JButton();
        lbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblContHilo1 = new javax.swing.JLabel();
        lblContHilo2 = new javax.swing.JLabel();
        lblContHilo3 = new javax.swing.JLabel();
        lblPrioridadHilo1 = new javax.swing.JLabel();
        lblPrioridadHilo2 = new javax.swing.JLabel();
        lblPrioridadHilo3 = new javax.swing.JLabel();

        btnMasPrioridad1.setText("++");
        btnMasPrioridad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasPrioridad1ActionPerformed(evt);
            }
        });

        btnMasPrioridad2.setText("++");
        btnMasPrioridad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasPrioridad2ActionPerformed(evt);
            }
        });

        btnMasPrioridad3.setText("++");
        btnMasPrioridad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasPrioridad3ActionPerformed(evt);
            }
        });

        btnFinalizar1.setText("Finalizar Hilo 1");
        btnFinalizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizar1ActionPerformed(evt);
            }
        });

        btnFinalizar2.setText("Finalizar Hilo 2");
        btnFinalizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizar2ActionPerformed(evt);
            }
        });

        btnFinalizar3.setText("Finalizar Hilo 3");
        btnFinalizar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizar3ActionPerformed(evt);
            }
        });

        btnMenosPrioridad1.setText("--");
        btnMenosPrioridad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosPrioridad1ActionPerformed(evt);
            }
        });

        btnMenosPrioridad2.setText("--");
        btnMenosPrioridad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosPrioridad2ActionPerformed(evt);
            }
        });

        btnMenosPrioridad3.setText("--");
        btnMenosPrioridad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosPrioridad3ActionPerformed(evt);
            }
        });

        btnFinalizarTodos.setText("FINALIZAR TODOS");
        btnFinalizarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarTodosActionPerformed(evt);
            }
        });

        lbl.setText("Hilo1:");

        jLabel2.setText("Hilo2:");

        jLabel3.setText("Hilo3:");

        jLabel4.setText("Pri:");

        jLabel5.setText("jLabel4");

        jLabel6.setText("Pri:");

        jLabel7.setText("Pri:");

        lblContHilo1.setText("0");

        lblContHilo2.setText("0");

        lblContHilo3.setText("0");

        lblPrioridadHilo1.setText("0");

        lblPrioridadHilo2.setText("0");

        lblPrioridadHilo3.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblContHilo2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblContHilo3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblContHilo1)))
                                .addGap(95, 95, 95)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblPrioridadHilo2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblPrioridadHilo3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblPrioridadHilo1))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnMenosPrioridad2)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnMasPrioridad1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnFinalizar1))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(btnMasPrioridad2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnFinalizar2))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(btnMasPrioridad3)
                                            .addGap(27, 27, 27)
                                            .addComponent(btnFinalizar3)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(26, 26, 26)
                                            .addComponent(btnMenosPrioridad1))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnMenosPrioridad3)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btnFinalizarTodos)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinalizar1)
                    .addComponent(btnMenosPrioridad1)
                    .addComponent(btnMasPrioridad1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMasPrioridad2)
                    .addComponent(btnFinalizar2)
                    .addComponent(btnMenosPrioridad2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMasPrioridad3)
                    .addComponent(btnFinalizar3)
                    .addComponent(btnMenosPrioridad3))
                .addGap(18, 18, 18)
                .addComponent(btnFinalizarTodos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl)
                    .addComponent(jLabel4)
                    .addComponent(lblContHilo1)
                    .addComponent(lblPrioridadHilo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(lblContHilo2)
                    .addComponent(lblPrioridadHilo2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(lblContHilo3)
                    .addComponent(lblPrioridadHilo3))
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizar1ActionPerformed
        hc1.interrumpir();
    }//GEN-LAST:event_btnFinalizar1ActionPerformed

    private void btnFinalizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizar2ActionPerformed
        hc2.interrumpir();
    }//GEN-LAST:event_btnFinalizar2ActionPerformed

    private void btnFinalizar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizar3ActionPerformed
        hc3.interrumpir();
    }//GEN-LAST:event_btnFinalizar3ActionPerformed

    private void btnFinalizarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarTodosActionPerformed
        hc1.interrumpir();
        hc2.interrumpir();
        hc3.interrumpir();
    }//GEN-LAST:event_btnFinalizarTodosActionPerformed

    private void btnMasPrioridad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasPrioridad1ActionPerformed
        hc1.setPriority(hc1.getPriority()+1);
    }//GEN-LAST:event_btnMasPrioridad1ActionPerformed

    private void btnMasPrioridad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasPrioridad2ActionPerformed
        hc2.setPriority(hc2.getPriority()+1);
    }//GEN-LAST:event_btnMasPrioridad2ActionPerformed

    private void btnMasPrioridad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasPrioridad3ActionPerformed
        hc3.setPriority(hc3.getPriority()+1);
    }//GEN-LAST:event_btnMasPrioridad3ActionPerformed

    private void btnMenosPrioridad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosPrioridad1ActionPerformed
        hc1.setPriority(hc1.getPriority()-1);
    }//GEN-LAST:event_btnMenosPrioridad1ActionPerformed

    private void btnMenosPrioridad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosPrioridad2ActionPerformed
        hc2.setPriority(hc2.getPriority()-1);
    }//GEN-LAST:event_btnMenosPrioridad2ActionPerformed

    private void btnMenosPrioridad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosPrioridad3ActionPerformed
        hc3.setPriority(hc3.getPriority()-1);
    }//GEN-LAST:event_btnMenosPrioridad3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar1;
    private javax.swing.JButton btnFinalizar2;
    private javax.swing.JButton btnFinalizar3;
    private javax.swing.JButton btnFinalizarTodos;
    private javax.swing.JButton btnMasPrioridad1;
    private javax.swing.JButton btnMasPrioridad2;
    private javax.swing.JButton btnMasPrioridad3;
    private javax.swing.JButton btnMenosPrioridad1;
    private javax.swing.JButton btnMenosPrioridad2;
    private javax.swing.JButton btnMenosPrioridad3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblContHilo1;
    private javax.swing.JLabel lblContHilo2;
    private javax.swing.JLabel lblContHilo3;
    private javax.swing.JLabel lblPrioridadHilo1;
    private javax.swing.JLabel lblPrioridadHilo2;
    private javax.swing.JLabel lblPrioridadHilo3;
    // End of variables declaration//GEN-END:variables
}
